name: input and context variable
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: choose the env to deploy
        required: true
        default: dev
        options:
          - dev
          - prod
          - test
          - review
      artifact_tag:
        description: choose the git tag to deploy
        required: true

jobs:
  taking_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy the app
        run: echo "deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"
      - name: workflow triggered event
        run: echo "workflow triggered name ${{github.event_name}}"
      - name: repo name
        run: echo "repositry ame is ${{github.repository}}"
      - name: git ref name
        run: echo "ref name is ${{github.ref}}"
      - name: username of repo
        run: echo "username of repo is ${{github.actor}}"
      - name: workflow file name
        run: echo "workflow file is ${{github.workflow}}"        
