name: input demo
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: choose the env to deploy
        required: true
        default: dev
        options:
          - dev
          - prod
          - test
          - review
      artifact_tag:
        description: choose the git tag to deploy
        required: true

jobs:
  taking_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy the app
        run: echo "deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"
