name: ci/cd pipeline
on:
  push:
    branches: [main]  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: check out repo code
        run: |
            npm install 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
      - name: check the testing
        run: |
         ls -l
         cd /src
         echo "test start"      
         npm install 
         npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: deploy the code
        run: |
         npm install
         node -v      

    
  
