name: env demo
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  APP_ENV: "dev"

jobs:
  build:
    env:
      APP_ENV: "dev jobs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: connecting to env
        env:
          APP_ENV: "dev steps"
        run: echo "app is connecting to $APP_ENV"
